### ISSUE TITLE
Go Modules Import Error

### ISSUE THREAD

**Issue by n8maninger** [lukechampine/us#10]
Not necessarily an issue, but something I thought you might want to be aware of. When importing `lukechampine.com/us` using Go Modules `us` throws an error importing in Sia/persist. Works fine the traditional way.

```
# gitlab.com/NebulousLabs/Sia/persist
../../../Projects/pkg/mod/gitlab.com/!nebulous!labs/!sia@v1.4.0/persist/boltdb.go:6:2: imported and not used: "github.com/coreos/bbolt"
../../../Projects/pkg/mod/gitlab.com/!nebulous!labs/!sia@v1.4.0/persist/boltdb.go:13:2: undefined: bolt
```

Reproduction:
https://github.com/n8maninger/sia-us-module

Modules:
https://github.com/golang/go/wiki/Modules

**Comment by lukechampine** [comment]
Hmm, I'll look into this. I plan to adopt modules in `us` eventually -- actually, I've already tried twice, but ran into problems (both with go.mod and editor integration) that I assume stemmed from immaturity. So I decided to hold off until modules are made the default in Go 1.13. Still, it would be nice if `us` could be used in projects using modules before then.

**Comment by lukechampine** [comment]
The error is kind of surprising: the imported package is actually `bolt`, but its import path ends in `bbolt`, and this seems to confuse the tooling. Such imports aren't some rare edge case, so why can't the tooling handle them?

Anyway, I found a temporary workaround: first, give the import an explicit name, like so:
```diff
--- a/persist/boltdb.go
+++ b/persist/boltdb.go
@@ -3,7 +3,7 @@ package persist
 import (
        "time"
 
-       "github.com/coreos/bbolt"
+       bolt "github.com/coreos/bbolt"
 )
 
 // BoltDatabase is a persist-level wrapper for the bolt database, providing

```
then add a replace directive to your `go.mod`:
```
replace gitlab.com/NebulousLabs/Sia => /home/user/go/src/gitlab.com/NebulousLabs/Sia
```
Unfortunately, `replace` only works with other modules, so you'll also need to create a (dummy) `go.mod` in `NebulousLabs/Sia` with `go mod init`. But after that, it should work.

**Comment by lukechampine** [comment]
The v1.4.1 release of Sia fixed these issues, so I've added a `go.mod` file to `us`. It seems to work, with one exception: importing `gitlab.com/NebulousLabs/Sia/modules/consensus` fails with:
```
../../../pkg/mod/gitlab.com/!nebulous!labs/!sia@v1.4.1/modules/consensus/accept.go:292:22: undefined: bbolt.MmapError
```
It seems that the vendored dependency is not being used for some reason. Perhaps `replace` directives are only respected in top-level modules? You can fix the error by adding a `replace` directive for `bbolt` in your top-level `go.mod`. Long-term, it seems like Sia v1.4.2 should move its vendored dependencies to proper forks (with their own `go.mod` files).
