### ISSUE TITLE
Keys in MetaDB

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/us#101]
It'd be helpful if MetaDB provides a function that retrieves keys stored in the DB.
Since the number of keys might be huge, a callback-based API seems better.

Relate to #67.

**Comment by lukechampine** [comment]
Yeah, I was thinking about this in the context of operations like `Migrate`. An iterator API would be preferable, but that would require locking the DB until the iterator was destroyed. So we'll probably do `kv.ForEach(func(key []byte))` instead.

**Comment by jkawamoto** [comment]
That looks good to me!

**Comment by jkawamoto** [comment]
Looks like this is implemented with bdaf6ee7b31c56429df727a510f5564285a3b9f5.
