### ISSUE TITLE
UploadChunk should fail if there is no available hosts

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/us#105]
This code looks like if there are no new hosts, it keeps using the same host, which fails to upload a chunk. 
https://github.com/lukechampine/us/blob/68b2c1b96a7bbab137b3d0fc98aac0b23fd131f5/renter/renterutil/strategies.go#L215-L222

I think it'll keep failing and it should fail with `errs` something like this:

```go
if len(errs) > len(pcu.Hosts.sessions)-len(shards) {
    close(reqChan)
    return errs
}
```

**Comment by lukechampine** [comment]
Thanks, this should be fixed by 88c39c2
