### ISSUE TITLE
Compile us to a C library for mobile integration

### ISSUE THREAD

**Issue by rlkelly** [lukechampine/us#11]
If you could compile `us` to C it could be used on mobile, this would create a lot of interesting possibilities.

**Comment by lukechampine** [comment]
I've researched `gomobile` a bit more, and I think a mobile integration is totally doable.

`gomobile` has some [restrictions](https://godoc.org/golang.org/x/mobile/cmd/gobind) around its bindings, like "Functions must return either no results, one result, or two results where the type of the second is the built-in 'error' type." Clearly there are lots of `us` functions that break this rule, so I was worried that building `us` on mobile was hopeless.

However, I was mistaken: the restrictions only apply to the package you want to *bind*, not all of the packages you depend on. Which means that you can write a "wrapper" package around `us` that calls all sorts of `us` functions, but whose API is compatible with `gomobile`.

So really the only thing required for an `us` mobile app is to write that wrapper. I don't think writing it will be hard at all; it's more a question of how to design the wrapper API. I assume the ideal wrapper will depend on what you want your app to do, so I probably won't include any such wrappers in the main `us` repo.

Anyway, I'll leave this open until there's been a successful demo of `us` on a phone. :)

**Comment by rlkelly** [comment]
sounds good, if I have some time this weekend I'll take a stab at it

**Comment by lukechampine** [comment]
I wrote some preliminary bindings here: https://github.com/lukechampine/us-bindings

I'll close this issue and move discussion to that repo.
