### ISSUE TITLE
Siacoin inputs do not equal siacoin outputs for transaction

### ISSUE THREAD

**Issue by MeijeSibbel** [lukechampine/us#112]
```
failed to renew the contract | RenewAndClearContract: ReadResponse: consensus conflict: provided transaction set is standalone and invalid: siacoin inputs do not equal siacoin outputs for transaction
```
We get quite a lot of these errors messages, about 70k in our logs every 24h / 450k every month. I would say that's quite a bit of failure to continue unaddressed. 

![image](https://user-images.githubusercontent.com/11735738/91434502-2d71e000-e865-11ea-9e20-5213e6eb0057.png)

450k a month;

![image](https://user-images.githubusercontent.com/11735738/91434809-a83afb00-e865-11ea-9e44-3f41f2a93db3.png)

Are there any options for us to address this?

> cschinnerlToday at 2:09 PM
This would be a bug in us. You should bring that up with Luke. Looks like the transactions are not valid and get rejected by consensus itself.

**Comment by lukechampine** [comment]
since the error is happening only in `RenewAndClearContract`, I suspect that this is related to https://github.com/lukechampine/us/issues/75. I'll have to closely compare how the renter and host construct the transaction.

**Comment by lukechampine** [comment]
can you confirm whether:

1. This happens with multiple different hosts, or just one?
2. This happens only in `RenewAndClearContract`, or also in `FormContract`?

**Comment by jkawamoto** [comment]
It happens for multiple different hosts. 
It also happens during `FormContract` but it less happens than `RenewAndClearContract` (we got 150 in the last month).

**Comment by lukechampine** [comment]
I see. So probably not related to #75 after all, then.

At this point I think the fastest way to debug would be to log the full transaction that's being rejected. Can you run this patch?

```diff
diff --git a/renter/proto/formcontract.go b/renter/proto/formcontract.go
index 212fc72..3d82d1a 100644
--- a/renter/proto/formcontract.go
+++ b/renter/proto/formcontract.go
@@ -2,8 +2,11 @@ package proto
 
 import (
        "crypto/ed25519"
+       "encoding/json"
+       "fmt"
        "math/big"
        "reflect"
+       "strings"
        "time"
 
        "github.com/pkg/errors"
@@ -217,6 +220,13 @@ func (s *Session) FormContract(w Wallet, tpool TransactionPool, key ed25519.Priv
        // Read the host signatures.
        var hostSigs renterhost.RPCFormContractSignatures
        if err := s.sess.ReadResponse(&hostSigs, 4096); err != nil {
+               if strings.Contains(err.Error(), "do not equal") {
+                       hostParents, _ := json.Marshal(resp.Parents)
+                       ourParents, _ := json.Marshal(parents)
+                       ourTxn, _ := json.Marshal(txn)
+                       fmt.Printf("host returned 'do not equal' error:\nhostParents:\n%s\nourParents:\n%s\nourTxn:\n%s\n",
+                               hostParents, ourParents, ourTxn)
+               }
                return ContractRevision{}, nil, err
        }
        txn.TransactionSignatures = append(txn.TransactionSignatures, hostSigs.ContractSignatures...)
```

**Comment by MeijeSibbel** [comment]
cc: log posted on discord.
