### ISSUE TITLE
AddShard uses bucketChunks to calculate the next ID 

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/us#135]
I think it's not a big problem but `AddShard` should use `bucketShards` to generate an ID (L242).

https://github.com/lukechampine/us/blob/289e2b3f9c1bfadfa121cf85c0c3e5074d77ded4/renter/renterutil/metadb.go#L240-L251

**Comment by lukechampine** [comment]
Fixed in https://github.com/lukechampine/us/commit/2534d6c592d728a2fe3621ad4ea89fa88c264faa
