### ISSUE TITLE
Conversion from untyped int to string yields a string of one rune, not a string of digits

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/us#139]
Testing renterhost package fails with this message:

```go
# lukechampine.com/us/renterhost
renterhost/session.go:470:33: conversion from untyped int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
```

https://github.com/lukechampine/us/blob/9bf8a3763e9bbe9c62505964f5dfbf4ffdd592ab/renterhost/session.go#L470

**Comment by lukechampine** [comment]
yeah, this is a new `vet` check added in Go 1.15. I have a fix on another branch, but I'll push it to master if you need it.

**Comment by jkawamoto** [comment]
I think this should be fixed. `bytes.Trim(s[:], string(0))` trims null characters from `s`, but I think it's not the expected behaviour. I'm wondering if this causes some problems.

**Comment by lukechampine** [comment]
trimming null bytes is the expected behavior. We're just printing a `Specifier` in human-readable format, but specifiers are always 16 bytes long, so if the name is shorter, there are zeros at the end. So we trim those.

**Comment by jkawamoto** [comment]
Thank you for fixing this!
