### ISSUE TITLE
Rejected for low paying host missed output

### ISSUE THREAD

**Issue by MeijeSibbel** [lukechampine/us#156]
All uploads are failing with the latest `us`/`shard`/`walrus` releases with the below error:

`Write: host rejected Write request: communication error: host expected to post at most 2546649664272686120960 collateral, but contract has host posting 2676703573154624051002: rejected for low paying host missed output\nc8c3bb55`

Log:
[gateway.log](https://github.com/lukechampine/us/files/5811951/gateway.log)

**Comment by lukechampine** [comment]
Do previous versions of `us` work?
Do any hosts succeed?
Do the hosts reporting this error all have the same version?

This will help identify whether the root cause is `us` or the host.

**Comment by jkawamoto** [comment]
Previous versions of `us` have worked for a long time, but we now get that error starting a couple of days ago. 
We can upload files without that error with some hosts, but I don't see any connection because that error is returned for not only v1.5.4 but also previous versions of hosts.

**Comment by MeijeSibbel** [comment]
![image](https://user-images.githubusercontent.com/11735738/104568252-27cc3980-5650-11eb-87b3-62caa7077c9f.png)

It looks like we've had this issue before but your fix @lukechampine didn't stick.

**Comment by jkawamoto** [comment]
I tried subtracting 10% and 20%, but neither of them works.

**Comment by lukechampine** [comment]
looks like this was caused by the `shard` blockheight being out of date.
I wonder if we can guard against this somehow, perhaps by estimating the blockheight (by time since genesis) and printing a warning if it differs by more than a few percent.
