### ISSUE TITLE
Delete files in parallel (ParallelSectorDeleter)

### ISSUE THREAD

**Issue by MeijeSibbel** [lukechampine/us#163]
Deletion data is currently done sequentially: <https://github.com/lukechampine/us/blob/11b24011224899f598f8326e8f95faffeebafb07/renter/renterutil/strategies.go#L1274>.

Our findings show that deleting buckets with tens of thousands of objects can take many days to complete. To speed up this process i suggest the implementation of Parallel Sector Deletion.

**Comment by lukechampine** [comment]
Added in dc4b3df. This is a simple implementation that deletes from every host in parallel; let me know if you run into any issues with it.

**Comment by MeijeSibbel** [comment]
Thank you Luke!!!
