### ISSUE TITLE
Investigate "rejected for high paying renter valid output" error

### ISSUE THREAD

**Issue by lukechampine** [lukechampine/us#18]
Hosts sometimes complain that we didn't pay them enough. I've tried to add some leeway here before, but it's surprisingly hard to quash this decisively. Warrants more investigation into how the host is calculating expected costs. (Perhaps related to BaseRPCPrice/SectorAccess/MerkleProof costs?)

**Comment by MeijeSibbel** [comment]
![image](https://user-images.githubusercontent.com/11735738/92222420-49960280-ee9f-11ea-86e1-160c7a00c878.png)

This error does occur in our logs however not very frequently. 

https://kibana.staging.storewise.tech/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-14d,to:now))&_a=(columns:!(msg,error,class.bucket,log,contractSet,class.gatewayID,size,candidates,usedHosts,grpc.method),filters:!(),index:'383b8090-c9a2-11ea-b8aa-bb4e5df8e11d',interval:auto,query:(language:kuery,query:'%22rejected%20for%20high%20paying%20renter%20valid%20output%22'),sort:!())

cc @jkawamoto .

**Comment by lukechampine** [comment]
Looks like these all occur during renewal, which means it's related to https://github.com/lukechampine/us/issues/80. Is it possible that these errors are all coming from the same host or contract?

**Comment by jkawamoto** [comment]
Last 2 weeks, the error happened with only this host
- `ed25519:f8d4d336ac91cdad92f1e150e2298d517375513d4b3f64d87069d4d118bbfed4` 

but multiple contracts with this host had the same issue.

**Comment by lukechampine** [comment]
I think this bug has finally been put to rest.
