### ISSUE TITLE
Ephemeral accounts for downloads (ReadonlyPseudoKV)

### ISSUE THREAD

**Issue by MeijeSibbel** [lukechampine/us#28]
Ephemeral accounts will be a very important keystone of StoreWise's `us` based architecture. From my understanding, following David's comments, it will have to be migrated from `siad` to `us` which is not trivial. Lets start with this as soon as possible please.

Reference: https://gitlab.com/NebulousLabs/Sia/merge_requests/3921

Read `accountmanager.go` and ;

SIP-0001
SIP-0002
SIP-0003
SIP-0006

**Comment by MeijeSibbel** [comment]
Edit: Since Ephemeral accounts don't resolve the contract upload lock, it's usefulness is limited and is thus of lower priority.

**Comment by MeijeSibbel** [comment]
The main handiness of this feature will be file sharing & content delivery since we won't have to create a contract set for every new download endpoint.

**Comment by jkawamoto** [comment]
It’d be nice if `us` integrates it as a something like ReadonlyPseudoFS.

**Comment by MeijeSibbel** [comment]
Migrated to https://github.com/lukechampine/us/issues/126.
