### ISSUE TITLE
Unwrap method to renterutil.HostError

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/us#46]
It'd be nice if `renterutil.HostError` implements [the Unwrap method](https://blog.golang.org/go1.13-errors#TOC_3.1.) so that we can check if the underlying error is, for example, [`host.errBadFileSize`](https://gitlab.com/NebulousLabs/Sia/-/blob/master/modules/host/negotiate.go#L29) by this clause:
```go
err := f() // f returns *renterutil.HostError
if errors.Is(err, host.errBadFileSize){
   ...
}
```
although we need `host` package to expose errBadFileSize.

**Comment by lukechampine** [comment]
Checking for specific host errors would also require the `renterhost` (or `proto`) package to translate error strings received over the wire into `error` variables. Probably a good idea, but unlikely to happen soon. `strings.Contains(err.Error(), "rejected for bad file size")` is brittle, but will work fine for the foreseeable future.

I'll go ahead and add an `Unwrap` method, though.

**Comment by jkawamoto** [comment]
It also needs to marshal/unmarshal errors so that it refers to the correct pre-defined error...

Anyway, thanks for fixing this quickly.

**Comment by jkawamoto** [comment]
All errors from hosts are wrapped with `renterhost.RPCError`, aren't they? Then, we only need `renterhost.RPCError` implements `Is` function to check specific host errors.
