### ISSUE TITLE
Upgrade Sia to v1.4.8

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/us#57]
This library still depends on v1.4.1:

https://github.com/lukechampine/us/blob/1389428cfbc6d4e60497822753e489b02e07f468/go.mod#L8

Would it be possible to upgrade v1.4.8?

**Comment by lukechampine** [comment]
We can upgrade easily enough, but do we need to? Is there new functionality that `us` can take advantage of?

**Comment by jkawamoto** [comment]
I just need to import some errors exported from 1.4.8 such as `host.ErrBadFileSize` :P

But, I’d also make sure that Sia client defined in v1.4.7 is compatible with siad v1.4.8?

**Comment by lukechampine** [comment]
If you're checking for `host.ErrBadFileSize` in your own code, you can import Sia@v1.4.8 in your own go.mod file. But if your intent is to PR a check into `us`, then yeah, we'll need to upgrade. In that case, you can just bump the version number along with the PR.

> But, I’d also make sure that Sia client defined in v1.4.7 is compatible with siad v1.4.8?

Good point. I don't think there are any changes that would break `us` (which only uses a few API calls anyway), but this is worth keeping in mind.

**Comment by jkawamoto** [comment]
I tried to set Sia@v1.4.8 on my go.mod but I got this error:

```
renter/renterutil/client.go:142:17: cannot use addr (type string) as type client.Options in argument to client.New
```

Unfortunately, it's not compatible with v1.4.8 on the very surface :P 
They changed the client constructor so that it takes options instead of address directly.

**Comment by lukechampine** [comment]
ah, right -- a change like that *should* be in a `v2`, i.e. a new import path, so the two packages could co-exist; but since they're both `v1`, the minimal version selection algorithm forces `us` to use v1.4.8, and it breaks.

I'll go ahead and bump our go.mod to v1.4.8.
