### ISSUE TITLE
Upload a file without encryption

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/us#59]
It'd be nice if `us` supports uploading/downloading files without encryption. Since some clients encrypt implement client-side encryption to achieve higher security, `us` could skip encryption and it might save transfer time.

**Comment by lukechampine** [comment]
I assume you mean adding no-encryption support to metafiles. I think I will continue to make encryption mandatory for metafiles, but if someone really wants to remove it, it shouldn't be too difficult to modify the format. ChaCha is really, really fast; multiple GB/s on desktops. Even on mobile, it's not going to add significant overhead compared to reedsolomon or blake2b. I'd rather keep things secure by default.

However, if `us` adds official support for Skynet, then it will likely support both encrypted and unencrypted skyfiles.

**Comment by jkawamoto** [comment]
Sorry for the late replay. 

I think even if ChaCha is fast enough, it'd be better to have an option to skip encryption because
- our clients or we encrypt files anyway; that means every file will be encrypted twice,
- mobile clients ask to save their battery as much as possible, and skipping one encryption can save some.
