### ISSUE TITLE
Session.Write should retry   

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/us#71]
Currently, once `Session.Write` fails; it kills the upper layer operation such as PseudoFile.Write and PseudoFS.Close. Since those functions are hard to recover, it creates some garbage if `Session.Write` with only one host fails. I think it'd be nice if `Session.Write` retries the request a couple of times.

Wrapping `Session.Write` with some library such as https://github.com/avast/retry-go would be enough. 

It is related to #69.

**Comment by lukechampine** [comment]
I'd need to be convinced that retrying actually increases the likelihood of success. In my experience, if a `Write` fails once, retrying the same `Write` will just fail again with the same error.  Retrying would only help if there was a temporary network failure, in which case you'd need to redial the host anyway.

**Comment by jkawamoto** [comment]
We observed retries worked after `i/o timeout` although we retried `PseudoFile.Write` at those times. 

If it needs to redial, do you mean we need to retry this function instead of `Session.Write`?
https://github.com/lukechampine/us/blob/365386b03c88e90bcd63381c94f8a7d8b5d8667b/renter/renterutil/fileops.go#L275-L290
