### ISSUE TITLE
Where is WalrusClient moved to?

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/us#77]
This PR https://github.com/lukechampine/us/pull/45 suggests WalrusClient was moved somewhere but I couldn't find it.
Will it be moved to https://github.com/lukechampine/walrus at some point?

**Comment by lukechampine** [comment]
You should be able to access this functionality via these adaptors: https://github.com/lukechampine/walrus/blob/master/client.go#L265-L275

**Comment by jkawamoto** [comment]
Found it. Thanks!
