### ISSUE TITLE
Output splitting

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/us#79]
We can form only about 10~20 contracts with one output. (Actually, we can form more contracts but we get `Lock: host rejected LoopLock request: no record of that contract` if we try to use such contracts) To form more contracts stably, we need to split outputs. This commit https://github.com/lukechampine/us/commit/72a1e2b30ff12e6ef8f08640c2b18ca7c9a1c854 looks like it implements something related to output splitting, but it looks like `DistributeFunds` is not used anywhere. Is that still WIP or do we need to implement something?

**Comment by lukechampine** [comment]
Currently, you will need to call `DistributeFunds` in your own code. I suppose it should probably be added to `walrus-cli` so that you don't need to write any custom code, though.

**Comment by jkawamoto** [comment]
I'm not sure how we should use `DistributeFunds`. Could you give examples?

**Comment by lukechampine** [comment]
Yeah, it's not the most user-friendly interface. `DistributeFunds` takes a set of inputs and a desired output value size, and tells you how many outputs you can create along with the leftover change. The use case is: you have a small number of high-value outputs, and you want a large number of small outputs.

Say you have a wallet with two outputs, each worth 1 million SC. You want to form lots of file contracts, and you know that no contract will cost more than 500 SC. You would construct the output-splitting transaction like so (simplified somewhat):

```go
inputs, _ := wc.UnspentOutputs(false)
splitAddr, _ := wc.NextAddress()
scPerOutput := types.SiacoinPrecision.Mul64(500)
feePerByte, _ := wc.TransactionFee()
n, fee, change := wallet.DistributeFunds(inputs, scPerOutput, feePerByte)
outputs := make([]types.SiacoinOutput, n)
for i := range outputs {
    outputs[i].Value = scPerOutput
    outputs[i].UnlockHash = splitAddr
}
outputs = append(outputs, types.SiacoinOutput{
    Value:      change,
    UnlockHash: splitAddr,
}
txn := types.Transaction{
    SiacoinInputs:  inputs,
    SiacoinOutputs: outputs,
    MinerFees:      []types.Currency{fee},
}
```

...ok, I'll add a `walrus-cli` command for it 😅

**Comment by MeijeSibbel** [comment]
Follow-up question: How many outputs can Walrus handle?, can we create 10,000+ outputs, a million?

**Comment by lukechampine** [comment]
Okay, `split` command added in https://github.com/lukechampine/walrus-cli/commit/c9a168867b2ef5cf932cc4b0bd5bd99e164b742d
