### ISSUE TITLE
Integrate NewUnlockedSessionFromConn to PseudoFS and PseudoKV

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/us#94]
NewUnlockedSessionFromConn implemented with #93 would reduce this kind of error: "NewUnlockedSession: dial tcp 72.66.79.45:9982: connect: connection timed out". So, it'd be nice PseudoFS uses it by default.

Related to #67.

**Comment by lukechampine** [comment]
In https://github.com/lukechampine/us/pull/95 I added support for custom lock timeouts to `HostSet`, but I'm not sure how to support custom conns. Can you suggest an API?

**Comment by jkawamoto** [comment]
As same as #95, adding SetDialTimeout and SetHandshakeTimeout to HostSet would be good.

**Comment by lukechampine** [comment]
Ah, I was thinking we'd need to allow passing entire `net.Conn`s, but your suggestion should work fine.

**Comment by jkawamoto** [comment]
Alternatively, it'd be possible to add ConnectionOpener interface but I think it's too much.
